apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zy6b2wp9k-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e6db873ba1.jh1d.p3.openshiftapps.com/rhtap/rhtap-qe:dd65becb34fb2c6d67df233ae0b8118257cc39b4@sha256:ffe2496930903099b9d2efe8ed55bcd54f5cef1e751bf38b3311dbfd506b0058
          name: container-image
